spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jakarta-rest-api
    username: root
    password: gplgr1566
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update